# Usando uma imagem base do OpenJDK
FROM openjdk:21-jdk-slim

# Definindo o diretório de trabalho dentro do container
WORKDIR /app

# Copiando o arquivo .jar gerado pelo Maven para o container
COPY target/LojaVirtual-0.0.1-SNAPSHOT.jar app.jar

# Expondo a porta que o Spring Boot usará
EXPOSE 8080

# Comando para rodar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]